version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'usernamefordb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'usernamefordb'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Mysqlpassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Mysqlpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
  nginx:
    restart: always
    build: 
      dockerfile:  Dockerfile.dev
      context: ./nginx
    ports: 
      - '4000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - MYSQL_USER=usernamefordb
      - MYSQL_PASSWORD=Mysqlpassword
      - MYSQL_ROOTPASSWORD=Mysqlpassword
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=usernamefordb
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
